### ISSUE TITLE
启动时直接引导ROM (Directly boot ROM on startup)

### ISSUE THREAD

**Issue by djwadhwa** [ez-flash/omega-de-kernel#11]
是否有办法在Gameboy Advance启动时直接引导特定的ROM，而不必每次都从菜单中导航? (Is there a way to directly boot a specific ROM when the Gameboy Advance starts up, without having to navigate through the menus every time?)

谢谢(Thank you)

**Comment by f3bandit** [comment]
You can write a rom to nor flash and flip the mode B switch and power cycle them system it will boot to that rom every time until you change it to another rom.
