### ISSUE TITLE
boot loader splash

### ISSUE THREAD

**Issue by f3bandit** [ez-flash/omega-de-kernel#2]
Any way to compile the boot loader with a different splash than the blue and white ez-flash logo?

**Comment by ez-flash** [comment]
no way, the splash screen is written in the FPGA codes.

**Comment by f3bandit** [comment]
ok!?! so is there a way to compile a new splash the the fpga codes and the build the bootloader with the new fpga codes?

**Comment by ez-flash** [comment]
The fpga code is closed-source. blue ez-flash is trade-mark and unchangeale by third party.

**Comment by f3bandit** [comment]
oh ok I gotcha sorry for the trouble then. :)
