### ISSUE TITLE
Rumble on Goomba Color doesn't works anymore.

### ISSUE THREAD

**Issue by beta215** [ez-flash/omega-de-kernel#5]
After flashing the newest kernel version, rumble on Goomba Color stopped working - though it still works on GBA games.

Downgrading the kernel to the older one (Kernel 1.03), now rumble still doesn't works on Goomba Color either. Any clues about what might be happening?

I have an EZODE (revision B), using a clean 32GB microSD, verified GBC ROMs, and latest kernel build downloaded from https://www.ezflash.cn/zip/omegade%20k1.04-fw6.zip. This is really strange.

**Comment by ez-flash** [comment]
Please check the GAME RTC option at the bottom of the system settings menu to confirm whether it is turned off. When this option is turned off, the rumble function will also be turned off.

**Comment by beta215** [comment]
Now it works, thank you a lot!

It would be appreciated if this important fact was to be added to the manual. It seems pretty important, since due to that setting rumble doesn't works only in some places - and it isn't made evident even by the manual.
